### PR TITLE
fix: deploy and wrong mount

### PR DESCRIPTION
**Pull request by hblitza**
- There was a false override in the deploy script.
- wrong/unneeded nginx config mount for url-generator

@FritzHoing

### CODE REVIEW

**Comment by FritzHoing** [comment]
Good catch @hblitza !

**Review by FritzHoing — APPROVED** [review]

**Review by sdobbert — COMMENTED** [review]
I think the default.conf overwrite is necessary for the warning-api to work.

**Comment by FritzHoing** [comment]
@hblitza Do you remember why we removed the default.conf from the volumes?

**Comment by FritzHoing** [comment]
Will be opened in a new MR

**Pull request closed without merging**
