### PR TITLE
Removing leftovers from geoserver-init image

### PR DESCRIPTION
**Pull request by weskamm**
@hblitza @JakobMiksch please review

### CODE REVIEW

**Comment by JakobMiksch** [comment]
I do not understand why to remove the geoserver-init at all. Let's discuss this.

**Comment by weskamm** [comment]
My understanding was that we only use it for password change and i thought this could be handled easier by hand. But as you mentioned elsewhere, it also created datastores / workspaces, which i was not aware of anymore. So im not blocking if we want to keep this and close this PR

**Comment by JakobMiksch** [comment]
I would also prefer to set credentials with the GeoServer image directly. I will try that.

For creating workspaces, styles, contact information, etc. I find the "geoserver_init" still quite useful. So I would vote to keep it ( and close the PR)

**Comment by hblitza** [comment]
Works for me then.

**Comment by JakobMiksch** [comment]
I re-added the geoserver-init script here https://github.com/klips-project/klips-sdi/pull/57

Setting the credentials directly in the docker image should be possible, but is not an quick fix. Let's discuss if and how we would like to implement this

**Comment by JakobMiksch** [comment]
since #57 is merged, I am closing here

**Pull request closed without merging**
