### PR TITLE
Adapt nginx port to 81

### PR DESCRIPTION
**Pull request by hblitza**
To avoid struggle with native installed nginx on the server.  

@chrismayer @JakobMiksch @weskamm

### CODE REVIEW

**Review by JakobMiksch — APPROVED** [review]

**Review by JakobMiksch — COMMENTED** [review]
We need to adapt all documentation. @weskamm needs to update his PR for the web demo app

**Review by JakobMiksch — CHANGES_REQUESTED** [review]
We need adapt all docs

**Comment by weskamm** [comment]
Does the port need to be exposed at all? Only the workers are using that nginx via its name, so the port does not to need to be opened i think.

**Comment by JakobMiksch** [comment]
@weskamm good point. Indeed for the moment only the pygeoapi and the GeoServer use the COG directory. But we thought it might be useful for users to have access to the raw COGs as well. 

But the 'mocked webspace' indeed does not need to be available public at all

**Review by JakobMiksch — APPROVED** [review]

**Comment by hblitza** [comment]
Thanks, all remarks resolved.

**Comment by weskamm** [comment]
after discussing, all was well

**Pull request merged**
